# -*- coding: utf-8 -*-
"""clase 14/5/25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ki4Dv_Ple6l3250nEoNB3KEcZ2dqGol5
"""

contraseña = "A12334566782"
mayuscula = False
numero = False


for i in contraseña:
  if i.isupper():
    mayuscula = True
  if i.isdigit():
    numero = True
if len(contraseña) >= 8 and mayuscula and numero:
  print("La contraseña es segura")
else:
  print("La contraseña no es segura")



unidad = 1

if unidad <= 100:
  print("su impuesto es 0")
elif unidad > 100 and unidad <= 200:
  print ("su impuesto es ", unidad*0.5)
elif unidad > 200:
  print ("su impuesto es ", unidad*0.7)