# -*- coding: utf-8 -*-
"""clase12/5/25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb3hAxx3ajEb2oQ0EmjGoN_OZiYUSqtr
"""

cuenta = float(input("Ingrese el monto de la cuenta:"))
propina = cuenta * 0.1
total = cuenta + propina
print(f"total de la cuenta ${cuenta}")
print(f"propina ${propina}")
print(f"total de la cuenta con propina ${total}")



nombre = input("Ingrese su nombre:")
apellido = input ("ingrese su apellido:")
print(f"tu nuevo correo es {nombre}.{apellido}@keyinstitute.edu.sv" )