# -*- coding: utf-8 -*-
"""5.4.2sumadordevaloresposicionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FAztT9lY74jVLg5g6SF4Lotal3wWsNZB
"""

x = int(input("Agregue el número que desea sumar sus cifras: "))

while x >= 10:
    x = sum(int(d) for d in str(x))
    print("Suma intermedia:", x)
print("Resultado final:", x)