# -*- coding: utf-8 -*-
"""5.4.1adivinaelnumero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAPNt00G7qQlr0ldas6o11tQX54loLjM
"""

import random
x = random.randint(1,100)
for i in range (0,101):
  y = int(input("adivine un numero entre 1 y 100: "))
  if y > x:
    print ("el numero secreto es menor")
  elif y < x:
    print ("el numero secreto es mayor")
  elif y == x:
    print ("¡Felicidades! has adivinado el numero")
    break