# -*- coding: utf-8 -*-
"""6.2.1eliminarvaloresduplicados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iTBtnhlcNaVB1G4cXv4jU8cq4H0wp1N
"""

x = input("Ingrese su lista de números separados por espacio: ")
lista = x.strip().split()
sin_duplicados = []
for i in lista:
    if i not in sin_duplicados:
        sin_duplicados.append(i)
print(" ".join(sin_duplicados))