# -*- coding: utf-8 -*-
"""6.3.1numeroslider.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGn2JokeeOhfEkRheZ20YQewf0uFJWqN
"""

x = input("Ingrese su lista de números separados por espacio: ")
numeros = [int(n) for n in x.split()]
lideres = [numeros[-1]]

for i in range(len(numeros) - 2, -1, -1):
    if numeros[i] > lideres[0]:
        lideres.insert(0, numeros[i])

print(*lideres)