# -*- coding: utf-8 -*-
"""10.2.1diagonales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maynAYplExR2rT57Kjsxzn9uS4lgjah6
"""

N = int(input("Ingrese el tamaño de la matriz y despues los numeros de la matriz separados por comas:"))

matriz = []
for _ in range(N):
    fila = list(map(int, input().split(',')))
    matriz.append(fila)


diagonal_principal = [matriz[i][i] for i in range(N)]
diagonal_secundaria = [matriz[i][N - 1 - i] for i in range(N)]


print(diagonal_principal)
print(diagonal_secundaria)