# -*- coding: utf-8 -*-
"""10.3.1simetrica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xi854bd2lPb03tRmFIAMiBWSnmQFmOni
"""

N = int(input("Ingrese el tamaño de la matriz, y despues los numeros separados por comas: "))

matriz = []
for _ in range(N):
    fila = list(map(int, input().split(',')))
    matriz.append(fila)

simetrica = True
for i in range(N):
    for j in range(i + 1, N):
        if matriz[i][j] != matriz[j][i]:
            simetrica = False
            break

if simetrica:
    print("La matriz es simétrica")
else:
    print("La matriz no es simétrica")