# -*- coding: utf-8 -*-
"""10.3.2juegodelentorno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OM8U2-J6CQYHNgKjTqHGBgBXbnGcusZJ
"""

N = int(input("Ingrese el número de filas: "))
M = int(input("Ingrese el número de columnas: "))

matriz = []
for _ in range(N):
    fila = list(map(int, input().split(',')))
    matriz.append(fila)

direcciones = [(-1, -1), (-1, 0), (-1, 1),
               ( 0, -1),          ( 0, 1),
               ( 1, -1), ( 1, 0), ( 1, 1)]

resultado = []
for i in range(N):
    fila_resultado = []
    for j in range(M):
        conteo = 0
        for dx, dy in direcciones:
            ni, nj = i + dx, j + dy
            if 0 <= ni < N and 0 <= nj < M and matriz[ni][nj] == 1:
                conteo += 1
        fila_resultado.append(conteo)
    resultado.append(fila_resultado)

for fila in resultado:
    print(fila)